name: cleaning
channels:
    - intel
    - conda-forge
    - r
    - bioconda
dependencies:
    - python=3.8
    - pandas=1
    - pip
    - numpy
    - r-base
    - r-essentials 
    - tornado
    - jupyter
    - jupyterlab
    - rise
    - numexpr
    - matplotlib
    - xlrd
    - seaborn
    - pytables
    - openpyxl
    - xlrd
    - requests
    - sqlalchemy
    - h5py
    - xlrd
    - dask
    - psycopg2
    - h5py
    - pytables
    - pyarrow
    - scikit-learn
    - lxml
    - beautifulsoup4
    - seqkit
    - pyreadstat
    - gensim
    - nltk
    - pip:
        - sqlalchemy-utils
        - vaex
        - csvkit
        - imbalanced-learn
        - Metaphone
        - fuzzy
        - rpy2
